name: Bug Report
description: Report a bug.
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide detailed steps to replicate the bug. Make sure to describe the current behavior. If applicable, include full errors, stack traces, and/or relevant logs.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: |
        Provide the criteria that must be met in order for this issue to be considered fixed.
        Be specific, and consider potential edge cases. The criteria should be observable and testable.
      placeholder: |
        Given a user or system is in ... (a page, workflow, or state)
        And ... (optional other criteria that needs to be met)
        When the user ... (action)
        Then ... (expected outcome)
        And ... (additional observable outcome)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible reason(s)/Suggested Fix
      description: Provide any insights into what might be causing the issue or how to resolve it.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Branch, commit, and/or version
      description: Provide the branch, commit, and/or version you're using.
      placeholder: |
        branch: issue-1
        commit: abc123d
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment details
      description: Provide environment details (OS name and version, etc).
    validations:
      required: true
