name: Bug Report
description: Report a bug.
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Pprovide detailed steps to replicate the bug.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: |
        What actually happened?

        Include full errors, stack traces, and/or relevant logs.
    validations:
      required: true
  - type: input
    attributes:
      label: Version or branch
      description: Provide the version or branch you're using.
      placeholder: ex. issue-1 (branch) or 0.0.1 (version)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots with descriptions to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment details
      description: Provide environment details (OS name and version, etc).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional details
      description: Provide any other additional details about the problem.
    validations:
      required: false
