name: checks
on: [push, pull_request]
jobs:
  test_python:
    name: test python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt

      - name: Attempt build
        run: python3 -m cookiecutter --no-input python/

  precommit_hooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hook:
          - name: "Check EOF format"
            args: "end-of-file-fixer --all-files"
          - name: "Check trailing whitespace"
            args: "trailing-whitespace --all-files"
          - name: "Check line ending format"
            args: "mixed-line-ending --fix=lf --all-files"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt

      - name: ${{ matrix.hook.name }}
        run: pre-commit run ${{ matrix.hook.args }} --all-files
