name: checks
on: [push, pull_request]
jobs:
  test_python:
    name: test python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Set up uv
        uses: yezz123/setup-uv@v4

      - name: Install dependencies
        run: uv run pip install -r requirements.txt

      - name: Attempt build
        run: uv run cookiecutter --no-input python/
